package com.java.Model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_id
     *
     * @mbggenerated
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.manager
     *
     * @mbggenerated
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.depart_description
     *
     * @mbggenerated
     */
    private String departDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @mbggenerated
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.manager
     *
     * @return the value of department.manager
     *
     * @mbggenerated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.manager
     *
     * @param manager the value for department.manager
     *
     * @mbggenerated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.depart_description
     *
     * @return the value of department.depart_description
     *
     * @mbggenerated
     */
    public String getDepartDescription() {
        return departDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.depart_description
     *
     * @param departDescription the value for department.depart_description
     *
     * @mbggenerated
     */
    public void setDepartDescription(String departDescription) {
        this.departDescription = departDescription == null ? null : departDescription.trim();
    }
}